# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: UMAAS
email: gerald.oyudo@isslng.com
description:
  A service that takes care of the hassle and bassle of user management.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gerald_oyudo
github_username:  geraldoyudo

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-asciidoc
exclude:
  - Gemfile
  - Gemfile.lock
keep_files:
  - assets/snippets
collections:
  api:
    output: true
    permalink: /api/:path/
  references:
    output: true
    permalink: /references/:path/
  tutorials:
    output: true
    permalink: /tutorials/:path/
  guides:
    output: true
    permalink: /guides/:path/
  guides:
    output: true
    permalink: /events/:path/
